# 01.B: Organizing data into  Series and DataFrames with Pandas
Pandas comes with two main data structures: Series and DataFrame. A Series is like a dictionary with keys (also called indexes) and values. A DataFrame represents tabular data with one or more columns.

To use pandas, we first need to import it. Let's also import numpy.

In [2]:
import numpy as np
import pandas as pd

We can now create series and dataframes
## Series

### Creating a Series
We can create a Serices by providing an array of values.

In [3]:
s1 = pd.Series([10,20,30,40,50])
print(s1)

0    10
1    20
2    30
3    40
4    50
dtype: int64


Since we did not provide indexes for our data, numeric zero-based indexes (much like those for arrays) will be automatically provided.

We can also create a Series by providing custom indexes.

In [4]:
s2 = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
print(s2)


a    1
b    2
c    3
d    4
e    5
dtype: int64


Notice that indexes are not required to be unique. For example, we can create a Series with duplicate indexes

In [5]:
s3 = pd.Series([1,2,3,4,5], index=['a','b','b','c','c']) 
print(s3)

a    1
b    2
b    3
c    4
c    5
dtype: int64


We can create a Series from NumPy arrays.

In [6]:
snp = pd.Series(np.arange(2, 11, 2), index=['A','B','C','D','F']) 
print(snp)

A     2
B     4
C     6
D     8
F    10
dtype: int32


And indexes could be ranges

In [7]:
s4 = pd.Series(np.arange(2, 11, 2), index=np.arange(1, 6)) 
print(s4)

1     2
2     4
3     6
4     8
5    10
dtype: int32


### Accessing elements in a Series
We can use the indexes to extract and/or slice elements within a Series. For example, given the Series `s1`:

In [8]:
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

Here is its element at index 0:

In [9]:
s1[0]

10

and its elements at index 2, 3:

In [10]:
s1[[2,3]]

2    30
3    40
dtype: int64

or at the index range from 2 upto but not equal to 4

In [11]:
s1[2:4]

2    30
3    40
dtype: int64

And given the Series `s2`:

In [12]:
s2

a    1
b    2
c    3
d    4
e    5
dtype: int64

Here is the element at index 'c' followed by the elements from index 'b' to index 'd'

In [13]:
s2['c']

3

In [14]:
s2['b':'d']

b    2
c    3
d    4
dtype: int64

And for a Series with duplicate indexes such as:

In [15]:
s3

a    1
b    2
b    3
c    4
c    5
dtype: int64

using a duplicate index returns a Series of all the elements with that index.

In [16]:
s3['b']

b    2
b    3
dtype: int64

The above use of indexes is the same as using `.loc[]` with indexes between `[` and `]`. That is

In [17]:
print(snp['A':'D'])
print(s3['b'])

A    2
B    4
C    6
D    8
dtype: int32
b    2
b    3
dtype: int64


is the same as:

In [18]:
print(snp.loc['A':'D'])
print(s3.loc['b'])

A    2
B    4
C    6
D    8
dtype: int32
b    2
b    3
dtype: int64


But sometimes we want to use the position of the index rather than its actual value to access elements within a Series. We can use `.iloc[]` with zero-based numeric indexe positions between `[` and `]`. The postion 0 means the first index. Given the Series:

In [19]:
snp

A     2
B     4
C     6
D     8
F    10
dtype: int32

We can access its first element:

In [63]:
snp.iloc[0]

B     4
C     6
D     8
F    10
dtype: int32

And its last element:

In [21]:
snp.iloc[snp.size - 1]

10

With `.iloc` we can index and slice a Series in exactly the same way we can a one-dimensional numpy array. Here is for example how you select every other element in a Series.

In [22]:
snp.iloc[0::2]

A     2
C     6
F    10
dtype: int32

And speaking of numpy, we can extract the values of a Series as a numpy array

In [23]:
snp.values

array([ 2,  4,  6,  8, 10])

We can also extract its indexes as an array also:

In [24]:
snp.index

Index(['A', 'B', 'C', 'D', 'F'], dtype='object')

## DataFrames
A data frame is a table with columns and rows. You can think of each column on a DataFrame as a Series sharing the same indexes with all other columns. Each column has a name that can be used to access it.

### Creating DataFrames
The easiest way to create a DataFrame is by using a dictionary of arrays. The keys of this dictionary will become column names. Here is a DataFrame with 4 by 9 multiplication table.

In [25]:
mtable = pd.DataFrame({
    'byOne': [1,2, 3, 4, 5, 6, 7, 8, 9],
    'byTwo': [2, 4, 6, 8, 10, 12, 14, 16, 18],
    'byThree': [3, 6, 9, 12, 15, 18, 21, 24, 27],
    'byFour': [4, 8, 12, 16, 20, 24, 28, 32, 36]
})

mtable

byOne  byTwo  byThree  byFour
0      1      2        3       4
1      2      4        6       8
2      3      6        9      12
3      4      8       12      16
4      5     10       15      20
5      6     12       18      24
6      7     14       21      28
7      8     16       24      32
8      9     18       27      36

Since we did not provide indexes, pandas will create zero-based numeric indexed for us, just like it does for a Series.

We can use numpy arrays to create the same table:

In [26]:
mtable = pd.DataFrame({
    'byOne': np.arange(1, 10),
    'byTwo': 2 * np.arange(1, 10),
    'byThree': 3 * np.arange(1, 10),
    'byFour': 4 * np.arange(1, 10)
})

print(mtable)

   byOne  byTwo  byThree  byFour
0      1      2        3       4
1      2      4        6       8
2      3      6        9      12
3      4      8       12      16
4      5     10       15      20
5      6     12       18      24
6      7     14       21      28
7      8     16       24      32
8      9     18       27      36


We can create a DataFrame from a two-dimensional array. Given an array:

In [27]:
table = np.array([
    np.arange(1, 10),
    2 * np.arange(1, 10),
    3 * np.arange(1, 10),
    4 * np.arange(1, 10)
]).T

print(table)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]
 [ 6 12 18 24]
 [ 7 14 21 28]
 [ 8 16 24 32]
 [ 9 18 27 36]]


we can create a DataFrame from it.

In [28]:
mtable = pd.DataFrame(table)

mtable

0   1   2   3
0  1   2   3   4
1  2   4   6   8
2  3   6   9  12
3  4   8  12  16
4  5  10  15  20
5  6  12  18  24
6  7  14  21  28
7  8  16  24  32
8  9  18  27  36

Since we did not provide column names or indexes, Pandas provided numeric zero-based column names and indexes for us. We can provide custom column names to this DataFrame after it was created

In [29]:
mtable.columns= ['A', 'B', 'C', 'D']
mtable

A   B   C   D
0  1   2   3   4
1  2   4   6   8
2  3   6   9  12
3  4   8  12  16
4  5  10  15  20
5  6  12  18  24
6  7  14  21  28
7  8  16  24  32
8  9  18  27  36

We can provide the column names at the time of creating the DataFrame.

In [30]:
mt = pd.DataFrame(table, columns=['byOne', 'byTwo', 'byThree', 'byFour'])

mt

byOne  byTwo  byThree  byFour
0      1      2        3       4
1      2      4        6       8
2      3      6        9      12
3      4      8       12      16
4      5     10       15      20
5      6     12       18      24
6      7     14       21      28
7      8     16       24      32
8      9     18       27      36

We can also provide custom indexes.

In [31]:
mt = pd.DataFrame(table, 
                  columns=['byOne', 'byTwo', 'byThree', 'byFour'],
                  index=['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9'])

mt

byOne  byTwo  byThree  byFour
x1      1      2        3       4
x2      2      4        6       8
x3      3      6        9      12
x4      4      8       12      16
x5      5     10       15      20
x6      6     12       18      24
x7      7     14       21      28
x8      8     16       24      32
x9      9     18       27      36

We can convert the content of a DataFrame to a numpy array:

In [32]:
mt.values

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16],
       [ 5, 10, 15, 20],
       [ 6, 12, 18, 24],
       [ 7, 14, 21, 28],
       [ 8, 16, 24, 32],
       [ 9, 18, 27, 36]])

We can get its colum names:

In [33]:
mt.columns

Index(['byOne', 'byTwo', 'byThree', 'byFour'], dtype='object')

and its indexes:

In [34]:
mt.index

Index(['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9'], dtype='object')

### Adding new columns and rows to an existing DataFrame
Given the DataFrame:

In [35]:
mt

byOne  byTwo  byThree  byFour
x1      1      2        3       4
x2      2      4        6       8
x3      3      6        9      12
x4      4      8       12      16
x5      5     10       15      20
x6      6     12       18      24
x7      7     14       21      28
x8      8     16       24      32
x9      9     18       27      36

We can add a new column like this:

In [36]:
mt['byFive'] = 5 * np.arange(1, 10)

mt

byOne  byTwo  byThree  byFour  byFive
x1      1      2        3       4       5
x2      2      4        6       8      10
x3      3      6        9      12      15
x4      4      8       12      16      20
x5      5     10       15      20      25
x6      6     12       18      24      30
x7      7     14       21      28      35
x8      8     16       24      32      40
x9      9     18       27      36      45

And using the `.loc` we can add a new row like this:

In [37]:
mt.loc['x10'] = 10 * np.arange(1, 6)
mt

byOne  byTwo  byThree  byFour  byFive
x1       1      2        3       4       5
x2       2      4        6       8      10
x3       3      6        9      12      15
x4       4      8       12      16      20
x5       5     10       15      20      25
x6       6     12       18      24      30
x7       7     14       21      28      35
x8       8     16       24      32      40
x9       9     18       27      36      45
x10     10     20       30      40      50

### Dropping a column or a row from a DataFrame
We can use the `drop` method to remove a column from a DataFrame. Let's remove the column `byFive` we added above:

In [38]:
mt.drop(['byFive'], axis=1)

byOne  byTwo  byThree  byFour
x1       1      2        3       4
x2       2      4        6       8
x3       3      6        9      12
x4       4      8       12      16
x5       5     10       15      20
x6       6     12       18      24
x7       7     14       21      28
x8       8     16       24      32
x9       9     18       27      36
x10     10     20       30      40

Here `axis=1` referes to columns. To drop a row we use `axis=0` and provide a index instead of a column name.

In [39]:
mt.drop(['x10'], axis=0)

byOne  byTwo  byThree  byFour  byFive
x1      1      2        3       4       5
x2      2      4        6       8      10
x3      3      6        9      12      15
x4      4      8       12      16      20
x5      5     10       15      20      25
x6      6     12       18      24      30
x7      7     14       21      28      35
x8      8     16       24      32      40
x9      9     18       27      36      45

### DataFrame indexing and slicing
We can use the column names and indexes to access individual cells.

In [40]:
mt['byTwo']['x5']

10

To extract a single column, use its name:

In [41]:
mt['byThree']

x1      3
x2      6
x3      9
x4     12
x5     15
x6     18
x7     21
x8     24
x9     27
x10    30
Name: byThree, dtype: int32

And use an array of column names to extract multiple columns

In [42]:
mt[['byTwo', 'byFour']]

byTwo  byFour
x1       2       4
x2       4       8
x3       6      12
x4       8      16
x5      10      20
x6      12      24
x7      14      28
x8      16      32
x9      18      36
x10     20      40

Use `.loc` to access a specific row using its index:

In [43]:
mt.loc['x6']

byOne       6
byTwo      12
byThree    18
byFour     24
byFive     30
Name: x6, dtype: int32

Similarly we can extract rows using their index positiosn using `.iloc[]`. We can, for example extract the first row using the its index position `0` (the index itself is `x1`).

In [44]:
mt.iloc[0]

byOne      1
byTwo      2
byThree    3
byFour     4
byFive     5
Name: x1, dtype: int32

We can also use `.iloc` to access certain columns and rows based on their positions, much like the indexing and slicing of a two-dimensional numpy array. Here is the whole DataFrame:

In [78]:
mt.iloc[:, -1]

x1      5
x2     10
x3     15
x4     20
x5     25
x6     30
x7     35
x8     40
x9     45
x10    50
Name: byFive, dtype: int32

In the `[:, :]`, the first `:` refers to all rows and the second `:` refers to all columns.

Here is the slice from the third(position 2) row to the sixth (position 5) and from second column (position 1) to fifth column(position 4)

In [86]:
mt

byOne  byTwo  byThree  byFour  byFive
x1       1      2        3       4       5
x2       2      4        6       8      10
x3       3      6        9      12      15
x4       4      8       12      16      20
x5       5     10       15      20      25
x6       6     12       18      24      30
x7       7     14       21      28      35
x8       8     16       24      32      40
x9       9     18       27      36      45
x10     10     20       30      40      50

In [87]:
mt.iloc[:, -1]

10

In [88]:
mt.iloc[:, -1].value_counts() / mt.iloc[:, -1].count()

15    0.1
30    0.1
45    0.1
10    0.1
25    0.1
40    0.1
5     0.1
20    0.1
35    0.1
50    0.1
Name: byFive, dtype: float64

And here is every other column and row.

In [47]:
mt.iloc[::2, ::2]

byOne  byThree  byFive
x1      1        3       5
x3      3        9      15
x5      5       15      25
x7      7       21      35
x9      9       27      45

Finally we can use the methods `head` and `tail` to display the first couple of records at the top or the bottom of a DataFrame. This is useful for exploring large dataframes.

In [48]:
print(mt.head())
print(mt.head(6))

print(mt.tail())
print(mt.tail(7))

    byOne  byTwo  byThree  byFour  byFive
x1      1      2        3       4       5
x2      2      4        6       8      10
x3      3      6        9      12      15
x4      4      8       12      16      20
x5      5     10       15      20      25
    byOne  byTwo  byThree  byFour  byFive
x1      1      2        3       4       5
x2      2      4        6       8      10
x3      3      6        9      12      15
x4      4      8       12      16      20
x5      5     10       15      20      25
x6      6     12       18      24      30
     byOne  byTwo  byThree  byFour  byFive
x6       6     12       18      24      30
x7       7     14       21      28      35
x8       8     16       24      32      40
x9       9     18       27      36      45
x10     10     20       30      40      50
     byOne  byTwo  byThree  byFour  byFive
x4       4      8       12      16      20
x5       5     10       15      20      25
x6       6     12       18      24      30
x7       7     14       

### Summarizing dataframes
Given the following 50 by 10 DataFrame:

In [49]:
data = pd.DataFrame(np.random.randn(50,10), columns=list('ABCDEFGHIJ'))

In [50]:
data

A         B         C         D         E         F         G  \
0   0.011828  0.478912  0.758489  0.526412 -0.801148  0.617972 -0.469994   
1  -0.559604 -0.245533  0.497033  1.551069  0.442778 -0.954492  0.364423   
2   1.069968 -1.641832 -1.797974  0.728208 -0.054575  0.820923  0.457488   
3  -0.174621 -0.531786  1.782840  0.676547  0.319879 -1.133541  1.915762   
4  -0.017471  0.239185 -0.564748 -0.370364 -0.348792 -1.972841  0.973740   
5   0.353813  0.534750  0.978663 -0.603140  1.242317  0.265070 -1.192645   
6  -1.010889  1.336798 -2.411475  0.408607  0.447040 -0.840897  0.339272   
7   2.397117 -0.731375 -1.606751  0.599342 -0.527700 -0.564899  0.489906   
8  -0.665964 -0.846009 -0.905978 -0.270659 -2.345096  0.366546  1.381363   
9  -0.826431  0.500512 -0.373289 -1.964986  0.539851 -0.073630  0.636784   
10  0.695921  0.321606 -0.098961 -0.818871 -0.579959 -1.355829  0.290952   
11  0.495533 -0.137046 -1.354267  0.649526 -0.453058 -0.649599 -0.312955   
12 -2.235233 -0.931496  1.066021  0.075488 -0.674405 -0.409891  1.306381   
13  0.193580 -0.402351 -0.783184  0.250821 -1.987822 -0.045790  0.122980   
14 -1.674230 -1.268487  0.105513 -0.386073 -0.016361 -0.586792 -0.482793   
15  0.931909  2.168017 -0.017202  0.531155  0.263761  0.096464  0.249477   
16  0.384370 -0.306059 -1.139156 -1.074850  0.952041 -0.512554  1.707259   
17  0.720988 -0.128736  0.439470  0.471923  1.999491  1.221243 -1.230657   
18 -0.728084 -1.484429  0.776603 -0.511488  0.369721  0.392454 -1.089769   
19 -2.072185 -0.963733  1.094168  0.724480  1.019594 -0.410450  2.625603   
20 -0.264291  0.344159  0.533162 -0.272890  0.267963 -1.462711 -0.534822   
21  0.567539  1.467131 -1.553058 -0.817586  0.704598 -0.146285 -0.671810   
22 -0.587601  0.734513 -0.625702  0.913782 -0.333593  0.118506 -1.157445   
23 -0.855816  0.258714 -0.198412 -2.394347  1.049952  1.478831  0.196871   
24  0.434113  0.321394 -1.543373  0.516089 -0.027953 -1.841815  1.050293   
25  0.204167 -1.317027 -0.937032  1.738440  1.853704  1.384971 -0.062211   
26 -1.029730  0.605272 -0.413840 -0.804986  1.330116 -0.466408 -0.278676   
27 -0.792365 -0.033841  0.054339 -0.762756 -0.305731  0.700134  0.237341   
28 -0.576046  0.081179 -0.320628  0.103470 -1.374188  0.612361 -1.204298   
29 -0.119720 -1.967403  0.369995 -0.176945  0.860107 -0.563529  0.826652   
30  1.817421  0.067682  1.458247 -1.868765 -1.360959  0.013909  1.602576   
31 -0.804898 -0.207196 -1.357151 -1.044412 -0.181181 -1.955254  1.709085   
32 -1.174529  0.949859 -1.177934 -1.611261 -0.998007 -2.248915  0.124450   
33 -0.674040 -0.649035 -1.179048  1.395818  0.262192 -1.379181 -1.499639   
34 -0.476583 -0.264191 -1.264668  0.210804  0.620307  1.169088  0.083283   
35 -0.060890 -0.761918 -1.183492  0.424432  0.026073  1.246875 -0.674454   
36 -0.568932 -1.044478 -0.034724 -0.689122 -2.264713 -0.213532  0.496434   
37  1.328277 -2.792915  0.788496 -1.258104 -0.568672 -0.745679  0.830947   
38 -1.565060 -0.547723 -0.517863  0.325527  0.037390  0.246349 -0.286967   
39  0.458333 -0.584704 -0.567251 -0.981023 -0.731144 -1.267097  2.425828   
40 -0.919320  1.160835  0.118788  0.804472 -1.337550  1.480025  0.045040   
41 -2.089835  0.178445  0.911086 -0.777718  0.414021 -0.313028  0.998226   
42 -1.786794  0.042792  0.990992 -0.353290  0.509391 -0.897386 -1.472361   
43  0.143200 -0.462760 -0.085045 -0.966017  0.696977 -0.779457 -2.624948   
44 -0.549971 -0.120116  0.394985 -0.373668 -0.570926 -1.043570  0.859200   
45 -1.516443  0.232465  1.018829  0.149219  0.256541 -2.276041 -1.526132   
46  0.487262  1.065710 -1.457254  1.373715  0.293937 -0.357773  0.851175   
47 -0.001836 -1.724353 -0.469370  0.394772 -0.187333  0.973570 -0.388270   
48 -0.070132 -0.587987 -0.784415 -0.304579  0.610780  0.855804 -0.316597   
49 -2.365779 -0.163171 -1.336113  3.192835 -0.264244 -0.931282  1.217254   

           H         I         J  
0  -0.340481  1.412417  1.212917  
1  -0.943918 -1.237866 -1.356017  
2  -0.547502 -2.131332  0.597

We can statistically summarize it like this:

In [51]:
data.describe()

A          B          C          D          E          F  \
count  50.000000  50.000000  50.000000  50.000000  50.000000  50.000000   
mean   -0.322400  -0.195155  -0.278433  -0.054419  -0.018092  -0.286781   
std     1.016221   0.929764   0.973309   1.024120   0.933007   0.998159   
min    -2.365779  -2.792915  -2.411475  -2.394347  -2.345096  -2.276041   
25%    -0.848470  -0.710790  -1.168240  -0.773977  -0.558429  -0.922808   
50%    -0.370437  -0.150109  -0.346959  -0.050729   0.031732  -0.383832   
75%     0.376731   0.321553   0.482642   0.529969   0.532236   0.385977   
max     2.397117   2.168017   1.782840   3.192835   1.999491   1.480025   

               G          H          I          J  
count  50.000000  50.000000  50.000000  50.000000  
mean    0.178772  -0.121056   0.050710   0.047682  
std     1.093355   1.012961   0.945944   1.219341  
min    -2.624948  -2.539946  -2.131332  -2.115323  
25%    -0.479593  -0.713541  -0.660395  -0.838883  
50%     0.217106  -0.002659   0.092860  -0.190806  
75%     0.857194   0.416882   0.712552   0.822684  
max     2.625603   1.971345   2.059060   2.987886

We can also get the means of each column:

In [52]:
data.mean()

A   -0.322400
B   -0.195155
C   -0.278433
D   -0.054419
E   -0.018092
F   -0.286781
G    0.178772
H   -0.121056
I    0.050710
J    0.047682
dtype: float64

the variances of each column:

In [53]:
data.var()

A    1.032705
B    0.864461
C    0.947330
D    1.048823
E    0.870501
F    0.996321
G    1.195425
H    1.026091
I    0.894810
J    1.486792
dtype: float64

and the standard deviations of each column:

In [54]:
data.std()

A    1.016221
B    0.929764
C    0.973309
D    1.024120
E    0.933007
F    0.998159
G    1.093355
H    1.012961
I    0.945944
J    1.219341
dtype: float64

## Transposing DataFrames
We can transpose a DataFrame by reversing its columns and indexes.

In [55]:
data.transpose()

0         1         2         3         4         5         6   \
A  0.011828 -0.559604  1.069968 -0.174621 -0.017471  0.353813 -1.010889   
B  0.478912 -0.245533 -1.641832 -0.531786  0.239185  0.534750  1.336798   
C  0.758489  0.497033 -1.797974  1.782840 -0.564748  0.978663 -2.411475   
D  0.526412  1.551069  0.728208  0.676547 -0.370364 -0.603140  0.408607   
E -0.801148  0.442778 -0.054575  0.319879 -0.348792  1.242317  0.447040   
F  0.617972 -0.954492  0.820923 -1.133541 -1.972841  0.265070 -0.840897   
G -0.469994  0.364423  0.457488  1.915762  0.973740 -1.192645  0.339272   
H -0.340481 -0.943918 -0.547502 -0.968312  1.593322 -2.194153  0.354313   
I  1.412417 -1.237866 -2.131332  0.757162 -0.845243  0.608825  0.321273   
J  1.212917 -1.356017  0.597791  2.987886 -1.952166  0.793501 -0.489751   

         7         8         9   ...        40        41        42        43  \
A  2.397117 -0.665964 -0.826431  ... -0.919320 -2.089835 -1.786794  0.143200   
B -0.731375 -0.846009  0.500512  ...  1.160835  0.178445  0.042792 -0.462760   
C -1.606751 -0.905978 -0.373289  ...  0.118788  0.911086  0.990992 -0.085045   
D  0.599342 -0.270659 -1.964986  ...  0.804472 -0.777718 -0.353290 -0.966017   
E -0.527700 -2.345096  0.539851  ... -1.337550  0.414021  0.509391  0.696977   
F -0.564899  0.366546 -0.073630  ...  1.480025 -0.313028 -0.897386 -0.779457   
G  0.489906  1.381363  0.636784  ...  0.045040  0.998226 -1.472361 -2.624948   
H  0.148547  0.223426 -0.704267  ...  0.877708  0.651115 -0.990547 -1.217372   
I  0.224975 -0.619737  0.997303  ... -0.371885 -1.049826 -0.690601  0.215379   
J -1.024111 -0.864728 -0.851773  ...  0.573135 -0.458111 -1.292371 -0.425080   

         44        45        46        47        48        49  
A -0.549971 -1.516443  0.487262 -0.001836 -0.070132 -2.365779  
B -0.120116  0.232465  1.065710 -1.724353 -0.587987 -0.163171  
C  0.394985  1.018829 -1.457254 -0.469370 -0.784415 -1.336113  
D -0.373668  0.149219  1.373715  0.394772 -0.304579  3.192835  
E -0.570926  0.256541  0.293937 -0.187333  0.610780 -0.264244  
F -1.043570 -2.276041 -0.357773  0.973570  0.855804 -0.931282  
G  0.859200 -1.526132  0.851175 -0.388270 -0.316597  1.217254  
H -0.555362 -0.476999 -0.153659 -2.309951  1.971345 -0.414177  
I  0.722316  0.683257  0.084721 -0.348386 -0.605603 -0.466288  
J -1.038505  0.002332  2.811352 -2.115323 -0.800215 -0.885612  

[10 rows x 50 columns]

which is the same as:

In [56]:
data.T

0         1         2         3         4         5         6   \
A  0.011828 -0.559604  1.069968 -0.174621 -0.017471  0.353813 -1.010889   
B  0.478912 -0.245533 -1.641832 -0.531786  0.239185  0.534750  1.336798   
C  0.758489  0.497033 -1.797974  1.782840 -0.564748  0.978663 -2.411475   
D  0.526412  1.551069  0.728208  0.676547 -0.370364 -0.603140  0.408607   
E -0.801148  0.442778 -0.054575  0.319879 -0.348792  1.242317  0.447040   
F  0.617972 -0.954492  0.820923 -1.133541 -1.972841  0.265070 -0.840897   
G -0.469994  0.364423  0.457488  1.915762  0.973740 -1.192645  0.339272   
H -0.340481 -0.943918 -0.547502 -0.968312  1.593322 -2.194153  0.354313   
I  1.412417 -1.237866 -2.131332  0.757162 -0.845243  0.608825  0.321273   
J  1.212917 -1.356017  0.597791  2.987886 -1.952166  0.793501 -0.489751   

         7         8         9   ...        40        41        42        43  \
A  2.397117 -0.665964 -0.826431  ... -0.919320 -2.089835 -1.786794  0.143200   
B -0.731375 -0.846009  0.500512  ...  1.160835  0.178445  0.042792 -0.462760   
C -1.606751 -0.905978 -0.373289  ...  0.118788  0.911086  0.990992 -0.085045   
D  0.599342 -0.270659 -1.964986  ...  0.804472 -0.777718 -0.353290 -0.966017   
E -0.527700 -2.345096  0.539851  ... -1.337550  0.414021  0.509391  0.696977   
F -0.564899  0.366546 -0.073630  ...  1.480025 -0.313028 -0.897386 -0.779457   
G  0.489906  1.381363  0.636784  ...  0.045040  0.998226 -1.472361 -2.624948   
H  0.148547  0.223426 -0.704267  ...  0.877708  0.651115 -0.990547 -1.217372   
I  0.224975 -0.619737  0.997303  ... -0.371885 -1.049826 -0.690601  0.215379   
J -1.024111 -0.864728 -0.851773  ...  0.573135 -0.458111 -1.292371 -0.425080   

         44        45        46        47        48        49  
A -0.549971 -1.516443  0.487262 -0.001836 -0.070132 -2.365779  
B -0.120116  0.232465  1.065710 -1.724353 -0.587987 -0.163171  
C  0.394985  1.018829 -1.457254 -0.469370 -0.784415 -1.336113  
D -0.373668  0.149219  1.373715  0.394772 -0.304579  3.192835  
E -0.570926  0.256541  0.293937 -0.187333  0.610780 -0.264244  
F -1.043570 -2.276041 -0.357773  0.973570  0.855804 -0.931282  
G  0.859200 -1.526132  0.851175 -0.388270 -0.316597  1.217254  
H -0.555362 -0.476999 -0.153659 -2.309951  1.971345 -0.414177  
I  0.722316  0.683257  0.084721 -0.348386 -0.605603 -0.466288  
J -1.038505  0.002332  2.811352 -2.115323 -0.800215 -0.885612  

[10 rows x 50 columns]

### Sorting a DataFrame

We can sort indexes, column names, or the values of a DataFrame. For example, the following sorts the indexes (`axis=0`) of the DataFrame in an ascending order:

In [57]:
mt.sort_index(axis=0)

byOne  byTwo  byThree  byFour  byFive
x1       1      2        3       4       5
x10     10     20       30      40      50
x2       2      4        6       8      10
x3       3      6        9      12      15
x4       4      8       12      16      20
x5       5     10       15      20      25
x6       6     12       18      24      30
x7       7     14       21      28      35
x8       8     16       24      32      40
x9       9     18       27      36      45

The following sorts the columns (`axis=1`) of the DataFrame in a descending order:

In [58]:
mt.sort_index(axis=1, ascending=False)

byTwo  byThree  byOne  byFour  byFive
x1       2        3      1       4       5
x2       4        6      2       8      10
x3       6        9      3      12      15
x4       8       12      4      16      20
x5      10       15      5      20      25
x6      12       18      6      24      30
x7      14       21      7      28      35
x8      16       24      8      32      40
x9      18       27      9      36      45
x10     20       30     10      40      50

Here is how to sort the values a given a column

In [59]:
mt.sort_values('byThree', ascending=False)

byOne  byTwo  byThree  byFour  byFive
x10     10     20       30      40      50
x9       9     18       27      36      45
x8       8     16       24      32      40
x7       7     14       21      28      35
x6       6     12       18      24      30
x5       5     10       15      20      25
x4       4      8       12      16      20
x3       3      6        9      12      15
x2       2      4        6       8      10
x1       1      2        3       4       5

and here is how to sort a value of a given row

In [60]:
mt.sort_values('x5', ascending=False, axis=1)

byFive  byFour  byThree  byTwo  byOne
x1        5       4        3      2      1
x2       10       8        6      4      2
x3       15      12        9      6      3
x4       20      16       12      8      4
x5       25      20       15     10      5
x6       30      24       18     12      6
x7       35      28       21     14      7
x8       40      32       24     16      8
x9       45      36       27     18      9
x10      50      40       30     20     10

## CHALLENGE 01
Recreate the 12 times table (see https://www.mathsisfun.com/tables.html) one column at a time. Start by creating an empty DataFrame representing the table. Use a Series object to create the first column and add it to the table. Move on the next column and do the same. And so on for the remaining columns. Use may use loops and expressions to calculate the values of these columns and avoid hard-coding values and code repetition.

In [61]:
# TODO